name: "Issue Tracker"
description: "Keeps a main readme-esk file with all project issues for easy viewing."
author: "contactMe@peterjkingston.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
