name: "Issue Tracker"
description: "Keeps a main readme-esk file with all project issues for easy viewing."
author: "contactMe@peterjkingston.com"

inputs:
  MY_ISSUE:
    description: "The github issue object"
    required: true
  
  MY_DESTINATION: "The destination path of the issues summary file."
    required: true
    default: ./Issues.md
    
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
