name: IssueTracker

#on:
#  issues:
#    types: [ opened, edited, deleted ]
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Issue Tracker Action
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out Repository
        if: ${{github.event.name == "issues" && github.event.action == ""}}
        uses: actions/checkout@v2

      # Write issue summaries to the Issues.md file
      - name: Create or Modify Issues.md file
        if: ${{github.event.name == "issues" && github.event.action == ""}}
        uses: ../action-issueTracker
        with:
          MY_DESTINATION: ./Issues.md
          MY_ISSUE: $GITHUB_EVENT_PATH
